services:
    OutlineManager:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
        image: OutlineManager
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-2249}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        volumes:
            - ".:/var/www/html"
        networks:
            - OutlineManager
        restart: unless-stopped
networks:
    OutlineManager:
        driver: bridge
